### ISSUE TITLE
-z noexecstack

### ISSUE THREAD

**Issue by jtuttas** [andiwand/ptbridge#5]
Hello, I try to connect my Raspberry PI to Cisco Packet Tracer 7. I've downloaded you program to the Raspberry pi and try to connect PT on my Desktop. But during starting ptbridge I got the following Error:

```
Java HotSpot(TM) Client VM warning: You have loaded library /tmp/packetsocket866569321805906031 which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

```
So may be include the -z noexecstack option in the build Script may be solved the problem? Can you rebuild the jar with this option?

best regards

jtuttas

**Comment by jtuttas** [comment]
OK, got ist, the problem ist that the Raspberry PI 2 has a amr 32 BIT achritecture and you class "libpacketsocket.so" is compiled for a 64bit X86 System :-(

Do you see any possibility to run ptbridge on a Raspberry PI 2 ?

**Comment by prateekmanocha** [comment]
Hi jtuttas,

Can zou please help me over the below mentioned issue ?

usage: <ptbridge> [<interface> <pt_ip>:<pt_port> <password>]

default: eth0 192.168.15.101:38000 cisco
root@prateek-desktop:~/ptbridge-master# eth0 192.168.15.192:38000 cisco
eth0: command not found

**Comment by andiwand** [comment]
@jtuttas you find the packetsocket source here https://github.com/andiwand/packetsocket. i guess you could compile it for arm.

@prateekmanocha you need the executable befor giving its parameters.

**Comment by prateekmanocha** [comment]
@andiwand  can you please explain with an example because i tried with ptbridge.jar like : java -jar ptbridge.jar then it says Exception in thread "main" java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:580)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.<init>(Socket.java:429)
	at java.net.Socket.<init>(Socket.java:242)
	at at.stefl.ptbridge.ptmp.PTMPConnection.connect(PTMPConnection.java:160)
	at at.stefl.ptbridge.main.Main.main(Main.java:58)
Please help me !
