### ISSUE TITLE
not able to execute Jar executable 

### ISSUE THREAD

**Issue by prateekmanocha** [andiwand/ptbridge#7]
@andiwand  can you please explain with an example because i tried with ptbridge.jar like : java -jar ptbridge.jar then it says Exception in thread "main" java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:580)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.<init>(Socket.java:429)
	at java.net.Socket.<init>(Socket.java:242)
	at at.stefl.ptbridge.ptmp.PTMPConnection.connect(PTMPConnection.java:160)
	at at.stefl.ptbridge.main.Main.main(Main.java:58)
Please help me !

**Comment by prateekmanocha** [comment]
prateek@prateek-desktop:~/ptbridge-master$ ./ptbridge 192.168.15.192:38000 cisco 
bash: ./ptbridge: No such file or directory
It also gives an error if executed this way !!

**Comment by rodi2000** [comment]
Hi, I am also not able to connect my packet tracer instance with physical network. can you please suggest me that how did you've done that? @prateekmanocha
