### ISSUE TITLE
jar file exec cformat error

### ISSUE THREAD

**Issue by prateekmanocha** [andiwand/ptbridge#8]
@andiwand  Hi.. I am working over PTBridge for my master thesis topic and thanks for your guidance so far... but I need a bit more help of yours.  while i was runnning the caommand as shown below as per your guidance..

`prateek@prateek-desktop:~/ptbridge-master$ ./ptbridge.jar eth1 192.168.15.192:38000 cisco`

The output gives an error : 

> 
bash: ./ptbridge.jar: cannot execute binary file: Exec format error
> 
Please help me resolving the same at the earliest It is creating an hindrance in my thesis work. 

Regards,
Prateek

**Comment by prateekmanocha** [comment]
Hi I run this command 

> sudo

 apt install binfmt-support qemu qemu-user-static

> 

and after that I could run  the command  /ptbridge.jar eth1 192.168.15.192:38000 cisco
and the cloud appeared in my packet tracer instance but in my linux terminal there were errors like 

`java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)
java.lang.IllegalStateException: Unreachable section!
	at at.stefl.packetsocket.io.ExtendedDataInputStream.readShort(ExtendedDataInputStream.java:99)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:48)
	at at.stefl.packetsocket.pdu.formatter.Ethernet2FrameFormatter.parse(Ethernet2FrameFormatter.java:1)
	at at.stefl.packetsocket.pdu.formatter.GenericPDUFormatter.parse(GenericPDUFormatter.java:23)
	at at.stefl.ptbridge.traverser.EthernetTraverser$EthernetReceiver.run(EthernetTraverser.java:25)` 

can you guide me in this scenario please...
